/**
 * @file trigger_patterns_generated.cpp
 * @brief Auto-generated trigger pattern data
 *
 * DO NOT EDIT - Generated by build_triggers.py
 */

#include "pch.h"
#include "trigger_patterns_generated.h"

// Pattern: 60-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/60_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_60_2[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_60_2 = {
    .name = "60-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_60_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 60,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_60_2,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 36-1 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/36_1.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_36_1[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_36_1 = {
    .name = "36-1 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_36_1,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 1,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_36_1,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 36-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/36_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_36_2[] = {
    { 0, 1.6f, 3.5f },
    { 1, 0.7f, 1.3f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_36_2 = {
    .name = "36-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_36_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_36_2,
    .gapCount = 2,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 32-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/32_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_32_2[] = {
    { 0, 1.5f, 3.0f },
    { 1, 0.7f, 1.3f },
    { 2, 0.7f, 1.3f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_32_2 = {
    .name = "32-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_32_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 32,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_32_2,
    .gapCount = 3,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 135 Tooth + Home + Cam
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/multitooth_home/135_home_cam.yaml
const TriggerPatternData pattern_TT_135_HOME_CAM = {
    .name = "135 Tooth + Home + Cam",
    .id = trigger_type_e::TT_135_HOME_CAM,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = nullptr,
    .eventCount = 0,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = false,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = true,
    .hasThirdChannel = true,
    .knownOperationMode = true,
};

// Pattern: Dodge Neon 1995
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/dodge_neon_1995.yaml
static const GapSpec gaps_TT_DODGE_NEON_1995[] = {
    { 0, 1.6f, 3.5f },
};

const TriggerPatternData pattern_TT_DODGE_NEON_1995 = {
    .name = "Dodge Neon 1995",
    .id = trigger_type_e::TT_DODGE_NEON_1995,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_DODGE_NEON_1995,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 90.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Ford Aspire
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/ford_aspire.yaml
static const ToothSpec events_TT_FORD_ASPIRE[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 180.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 360.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

const TriggerPatternData pattern_TT_FORD_ASPIRE = {
    .name = "Ford Aspire",
    .id = trigger_type_e::TT_FORD_ASPIRE,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_FORD_ASPIRE,
    .eventCount = 4,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: GM 7X
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/gm_7x.yaml
static const ToothSpec events_TT_GM_7X[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 10.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 60.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 70.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 120.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 130.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 190.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 240.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 250.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 300.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 310.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 320.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 330.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_GM_7X[] = {
    { 0, 0.5f, 1.5f },
};

const TriggerPatternData pattern_TT_GM_7X = {
    .name = "GM 7X",
    .id = trigger_type_e::TT_GM_7X,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_GM_7X,
    .eventCount = 14,
    .gaps = gaps_TT_GM_7X,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Honda K-Series Crank 12-1
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/honda_k_12_1.yaml
static const GapSpec gaps_TT_HONDA_K_CRANK_12_1[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_HONDA_K_CRANK_12_1 = {
    .name = "Honda K-Series Crank 12-1",
    .id = trigger_type_e::TT_HONDA_K_CRANK_12_1,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 12,
    .missingTeeth = 1,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_HONDA_K_CRANK_12_1,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Mazda Miata NA
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/mazda_miata_na.yaml
static const ToothSpec events_TT_MAZDA_MIATA_NA[] = {
    { 4.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 8.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 66.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 70.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 352.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 356.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 700.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 704.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_MAZDA_MIATA_NA[] = {
    { 0, 3.0f, 20.0f },
};

const TriggerPatternData pattern_TT_MAZDA_MIATA_NA = {
    .name = "Mazda Miata NA",
    .id = trigger_type_e::TT_MAZDA_MIATA_NA,
    .operationMode = operation_mode_e::FOUR_STROKE_CAM_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_MAZDA_MIATA_NA,
    .eventCount = 8,
    .gaps = gaps_TT_MAZDA_MIATA_NA,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = false,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Nissan QR25
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/nissan_qr25.yaml
static const GapSpec gaps_TT_NISSAN_QR25[] = {
    { 0, 1.6f, 3.5f },
};

const TriggerPatternData pattern_TT_NISSAN_QR25 = {
    .name = "Nissan QR25",
    .id = trigger_type_e::TT_NISSAN_QR25,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_NISSAN_QR25,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Subaru 7-6
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/subaru_7_6.yaml
static const ToothSpec events_TT_SUBARU_7_6[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 5.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 30.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 35.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 60.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 65.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 90.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 95.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 120.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 125.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 150.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 155.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 185.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 540.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 545.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 570.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 575.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 600.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 605.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 630.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 635.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 660.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 665.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 690.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 695.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_SUBARU_7_6[] = {
    { 0, 3.0f, 20.0f },
};

const TriggerPatternData pattern_TT_SUBARU_7_6 = {
    .name = "Subaru 7-6",
    .id = trigger_type_e::TT_SUBARU_7_6,
    .operationMode = operation_mode_e::FOUR_STROKE_CAM_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_SUBARU_7_6,
    .eventCount = 26,
    .gaps = gaps_TT_SUBARU_7_6,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = false,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Toyota 2JZ 3-34
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/toyota_2jz_3_34.yaml
static const ToothSpec events_TT_2JZ_3_34_SIMULATION_ONLY[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 5.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 20.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 25.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 40.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 45.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_2JZ_3_34_SIMULATION_ONLY[] = {
    { 0, 3.0f, 20.0f },
};

const TriggerPatternData pattern_TT_2JZ_3_34_SIMULATION_ONLY = {
    .name = "Toyota 2JZ 3-34",
    .id = trigger_type_e::TT_2JZ_3_34_SIMULATION_ONLY,
    .operationMode = operation_mode_e::FOUR_STROKE_CAM_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_2JZ_3_34_SIMULATION_ONLY,
    .eventCount = 6,
    .gaps = gaps_TT_2JZ_3_34_SIMULATION_ONLY,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = false,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: One Plus One
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/one_plus_one.yaml
static const ToothSpec events_TT_ONE_PLUS_ONE[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 180.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 360.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

const TriggerPatternData pattern_TT_ONE_PLUS_ONE = {
    .name = "One Plus One",
    .id = trigger_type_e::TT_ONE_PLUS_ONE,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_ONE_PLUS_ONE,
    .eventCount = 4,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 3-1 Cam Pattern
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/3_1_cam.yaml
static const ToothSpec events_TT_3_1_CAM[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 60.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 240.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 360.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 420.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 540.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 600.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_3_1_CAM[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_3_1_CAM = {
    .name = "3-1 Cam Pattern",
    .id = trigger_type_e::TT_3_1_CAM,
    .operationMode = operation_mode_e::FOUR_STROKE_CAM_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_3_1_CAM,
    .eventCount = 8,
    .gaps = gaps_TT_3_1_CAM,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = false,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Half Moon
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/half_moon.yaml
const TriggerPatternData pattern_TT_HALF_MOON = {
    .name = "Half Moon",
    .id = trigger_type_e::TT_HALF_MOON,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 1,
    .missingTeeth = 0,
    .events = nullptr,
    .eventCount = 0,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Mercedes 2-Segment
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/mercedes_2_segment.yaml
static const ToothSpec events_TT_MERCEDES_2_SEGMENT[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 30.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 210.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

const TriggerPatternData pattern_TT_MERCEDES_2_SEGMENT = {
    .name = "Mercedes 2-Segment",
    .id = trigger_type_e::TT_MERCEDES_2_SEGMENT,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_MERCEDES_2_SEGMENT,
    .eventCount = 4,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Rover K-Series
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/rover_k.yaml
static const GapSpec gaps_TT_ROVER_K[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_ROVER_K = {
    .name = "Rover K-Series",
    .id = trigger_type_e::TT_ROVER_K,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 1,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_ROVER_K,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};


const TriggerPatternData* getTriggerPattern(trigger_type_e type) {
    switch(type) {
        case trigger_type_e::TT_TOOTHED_WHEEL_60_2:
            return &pattern_TT_TOOTHED_WHEEL_60_2;
        case trigger_type_e::TT_TOOTHED_WHEEL_36_1:
            return &pattern_TT_TOOTHED_WHEEL_36_1;
        case trigger_type_e::TT_TOOTHED_WHEEL_36_2:
            return &pattern_TT_TOOTHED_WHEEL_36_2;
        case trigger_type_e::TT_TOOTHED_WHEEL_32_2:
            return &pattern_TT_TOOTHED_WHEEL_32_2;
        case trigger_type_e::TT_135_HOME_CAM:
            return &pattern_TT_135_HOME_CAM;
        case trigger_type_e::TT_DODGE_NEON_1995:
            return &pattern_TT_DODGE_NEON_1995;
        case trigger_type_e::TT_FORD_ASPIRE:
            return &pattern_TT_FORD_ASPIRE;
        case trigger_type_e::TT_GM_7X:
            return &pattern_TT_GM_7X;
        case trigger_type_e::TT_HONDA_K_CRANK_12_1:
            return &pattern_TT_HONDA_K_CRANK_12_1;
        case trigger_type_e::TT_MAZDA_MIATA_NA:
            return &pattern_TT_MAZDA_MIATA_NA;
        case trigger_type_e::TT_NISSAN_QR25:
            return &pattern_TT_NISSAN_QR25;
        case trigger_type_e::TT_SUBARU_7_6:
            return &pattern_TT_SUBARU_7_6;
        case trigger_type_e::TT_2JZ_3_34_SIMULATION_ONLY:
            return &pattern_TT_2JZ_3_34_SIMULATION_ONLY;
        case trigger_type_e::TT_ONE_PLUS_ONE:
            return &pattern_TT_ONE_PLUS_ONE;
        case trigger_type_e::TT_3_1_CAM:
            return &pattern_TT_3_1_CAM;
        case trigger_type_e::TT_HALF_MOON:
            return &pattern_TT_HALF_MOON;
        case trigger_type_e::TT_MERCEDES_2_SEGMENT:
            return &pattern_TT_MERCEDES_2_SEGMENT;
        case trigger_type_e::TT_ROVER_K:
            return &pattern_TT_ROVER_K;
        default:
            return nullptr;
    }
}
