/**
 * @file trigger_patterns_generated.cpp
 * @brief Auto-generated trigger pattern data
 *
 * DO NOT EDIT - Generated by build_triggers.py
 */

#include "pch.h"
#include "trigger_patterns_generated.h"

// Pattern: 60-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/60_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_60_2[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_60_2 = {
    .name = "60-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_60_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 60,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_60_2,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 36-1 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/36_1.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_36_1[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_36_1 = {
    .name = "36-1 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_36_1,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 1,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_36_1,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 36-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/36_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_36_2[] = {
    { 0, 1.6f, 3.5f },
    { 1, 0.7f, 1.3f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_36_2 = {
    .name = "36-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_36_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_36_2,
    .gapCount = 2,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 32-2 Toothed Wheel
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/skipped_tooth/32_2.yaml
static const GapSpec gaps_TT_TOOTHED_WHEEL_32_2[] = {
    { 0, 1.5f, 3.0f },
    { 1, 0.7f, 1.3f },
    { 2, 0.7f, 1.3f },
};

const TriggerPatternData pattern_TT_TOOTHED_WHEEL_32_2 = {
    .name = "32-2 Toothed Wheel",
    .id = trigger_type_e::TT_TOOTHED_WHEEL_32_2,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 32,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_TOOTHED_WHEEL_32_2,
    .gapCount = 3,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: 135 Tooth + Home + Cam
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/multitooth_home/135_home_cam.yaml
const TriggerPatternData pattern_TT_135_HOME_CAM = {
    .name = "135 Tooth + Home + Cam",
    .id = trigger_type_e::TT_135_HOME_CAM,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = nullptr,
    .eventCount = 0,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = false,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = true,
    .hasThirdChannel = true,
    .knownOperationMode = true,
};

// Pattern: Dodge Neon 1995
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/dodge_neon_1995.yaml
static const GapSpec gaps_TT_DODGE_NEON_1995[] = {
    { 0, 1.6f, 3.5f },
};

const TriggerPatternData pattern_TT_DODGE_NEON_1995 = {
    .name = "Dodge Neon 1995",
    .id = trigger_type_e::TT_DODGE_NEON_1995,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 36,
    .missingTeeth = 2,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_DODGE_NEON_1995,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 90.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Ford Aspire
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/ford_aspire.yaml
static const ToothSpec events_TT_FORD_ASPIRE[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 180.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 360.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

const TriggerPatternData pattern_TT_FORD_ASPIRE = {
    .name = "Ford Aspire",
    .id = trigger_type_e::TT_FORD_ASPIRE,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_FORD_ASPIRE,
    .eventCount = 4,
    .gaps = nullptr,
    .gapCount = 0,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: GM 7X
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/gm_7x.yaml
static const ToothSpec events_TT_GM_7X[] = {
    { 0.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 10.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 60.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 70.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 120.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 130.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 180.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 190.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 240.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 250.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 300.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 310.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 320.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 330.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_GM_7X[] = {
    { 0, 0.5f, 1.5f },
};

const TriggerPatternData pattern_TT_GM_7X = {
    .name = "GM 7X",
    .id = trigger_type_e::TT_GM_7X,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::Rise,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_GM_7X,
    .eventCount = 14,
    .gaps = gaps_TT_GM_7X,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Honda K-Series Crank 12-1
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/honda_k_12_1.yaml
static const GapSpec gaps_TT_HONDA_K_CRANK_12_1[] = {
    { 0, 1.5f, 3.0f },
};

const TriggerPatternData pattern_TT_HONDA_K_CRANK_12_1 = {
    .name = "Honda K-Series Crank 12-1",
    .id = trigger_type_e::TT_HONDA_K_CRANK_12_1,
    .operationMode = operation_mode_e::FOUR_STROKE_CRANK_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::SKIPPED_TOOTH,
    .totalTeeth = 12,
    .missingTeeth = 1,
    .events = nullptr,
    .eventCount = 0,
    .gaps = gaps_TT_HONDA_K_CRANK_12_1,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = true,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};

// Pattern: Mazda Miata NA
// From: /home/runner/work/rusefi/rusefi/firmware/controllers/trigger/patterns/oem/mazda_miata_na.yaml
static const ToothSpec events_TT_MAZDA_MIATA_NA[] = {
    { 4.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 8.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 66.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 70.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 352.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 356.0f, EdgeType::FALL, TriggerChannel::CRANK },
    { 700.0f, EdgeType::RISE, TriggerChannel::CRANK },
    { 704.0f, EdgeType::FALL, TriggerChannel::CRANK },
};

static const GapSpec gaps_TT_MAZDA_MIATA_NA[] = {
    { 0, 3.0f, 20.0f },
};

const TriggerPatternData pattern_TT_MAZDA_MIATA_NA = {
    .name = "Mazda Miata NA",
    .id = trigger_type_e::TT_MAZDA_MIATA_NA,
    .operationMode = operation_mode_e::FOUR_STROKE_CAM_SENSOR,
    .syncEdge = SyncEdge::RiseOnly,
    .patternType = PatternType::CUSTOM,
    .totalTeeth = 0,
    .missingTeeth = 0,
    .events = events_TT_MAZDA_MIATA_NA,
    .eventCount = 8,
    .gaps = gaps_TT_MAZDA_MIATA_NA,
    .gapCount = 1,
    .useOnlyPrimaryForSync = true,
    .tdcPosition = 0.0f,
    .isCrankBased = false,
    .hasSecondChannel = false,
    .hasThirdChannel = false,
    .knownOperationMode = true,
};


const TriggerPatternData* getTriggerPattern(trigger_type_e type) {
    switch(type) {
        case trigger_type_e::TT_TOOTHED_WHEEL_60_2:
            return &pattern_TT_TOOTHED_WHEEL_60_2;
        case trigger_type_e::TT_TOOTHED_WHEEL_36_1:
            return &pattern_TT_TOOTHED_WHEEL_36_1;
        case trigger_type_e::TT_TOOTHED_WHEEL_36_2:
            return &pattern_TT_TOOTHED_WHEEL_36_2;
        case trigger_type_e::TT_TOOTHED_WHEEL_32_2:
            return &pattern_TT_TOOTHED_WHEEL_32_2;
        case trigger_type_e::TT_135_HOME_CAM:
            return &pattern_TT_135_HOME_CAM;
        case trigger_type_e::TT_DODGE_NEON_1995:
            return &pattern_TT_DODGE_NEON_1995;
        case trigger_type_e::TT_FORD_ASPIRE:
            return &pattern_TT_FORD_ASPIRE;
        case trigger_type_e::TT_GM_7X:
            return &pattern_TT_GM_7X;
        case trigger_type_e::TT_HONDA_K_CRANK_12_1:
            return &pattern_TT_HONDA_K_CRANK_12_1;
        case trigger_type_e::TT_MAZDA_MIATA_NA:
            return &pattern_TT_MAZDA_MIATA_NA;
        default:
            return nullptr;
    }
}
