#!/bin/bash
# This script reads triggers.txt generated by unit_test binary and produces a bunch of trigger shapes .png files
# these images placed into unit_tests/triggers
# and later manually published at https://rusefi.com/images/triggers/

set -e

cd ../unit_tests
make -j4

if [ ! -f build/rusefi_test ]; then
    echo "UNIT TEST COMPILATION FAILED"
    exit 1
fi

ls -l build/rusefi_test

rm -f triggers.txt
build/rusefi_test
pwd

if [ ! -f triggers.txt ]; then
    echo "triggers.txt generation FAILED"
    exit 1
fi

# Build the trigger-ui jar if it doesn't exist
cd ../java_tools
./gradlew :trigger-ui:shadowJar

# Run the TriggerImage Java tool with virtual framebuffer
cd ../unit_tests
xvfb-run -a java -cp ../java_console/trigger-ui/build/libs/trigger-ui-all.jar com.rusefi.trigger.TriggerImage
